# Generated by Django 6.0.7 on 2026-07-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jid", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("is_group", models.BooleanField(default=False)),
                ("scoped", models.BooleanField(default=False)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="WaMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                (
                    "sender_jid",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out")],
                        default="in",
                        max_length=8,
                    ),
                ),
                ("body", models.TextField()),
                ("ts", models.DateTimeField(db_index=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="pipelines.wachat",
                    ),
                ),
            ],
            options={
                "ordering": ["-ts"],
                "unique_together": {("chat", "external_id")},
            },
        ),
    ]
