"""Live `state:` blocks for workspace connector YAMLs.

The connector files declare *capability* (hand-authored); this module keeps a
`state:` section in each one current — connection status, the scoped chat
directory, and the exact fetch-step shape workflows must use. The agent reads
one file to author a workflow, and the engine honours the same contract when
it runs, so the yaml is a single source of truth for both.

Called (best-effort, never raising) from: whatsapp pair, gmail connect/refresh,
chat scope toggles and chat sync.
"""

import logging
import os
from datetime import datetime, timezone
from pathlib import Path

import yaml
from django.conf import settings

logger = logging.getLogger(__name__)


def _connectors_dir():
    root = os.environ.get("AGENT_WORKSPACE_ROOT") or str(
        Path(settings.BASE_DIR).parent / "workspace"
    )
    return Path(root) / "connectors"


def _now():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _write_state(name, state):
    path = _connectors_dir() / f"{name}.yaml"
    try:
        doc = yaml.safe_load(path.read_text()) or {}
    except FileNotFoundError:
        logger.warning("connector file missing: %s", path)
        return
    doc["state"] = state
    path.write_text(
        "# Capability declared by hand; `state:` is auto-generated by the backend\n"
        "# (pair / connect / scope / sync events) — do not edit state manually.\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)
    )


def refresh_whatsapp():
    from crm.models import Connection
    from pipelines.models import WaChat

    conn = Connection.objects.filter(source="whatsapp").first()
    scoped = WaChat.objects.filter(scoped=True).order_by("-last_message_at")
    total = WaChat.objects.count()
    scoped_list = [
        {
            "jid": c.jid,
            "name": c.name or "",
            "is_group": c.is_group,
            "message_count": c.messages.count(),
            "last_message_at": c.last_message_at.isoformat() if c.last_message_at else None,
        }
        for c in scoped
    ]
    _write_state(
        "whatsapp",
        {
            "status": (conn.status if conn else "disconnected"),
            "updated_at": _now(),
            "chats": {
                "scoped": scoped_list,
                "scoped_count": len(scoped_list),
                "total_seen": total,
                "note": "only scoped chats are fetchable; toggle scope on the connections page",
            },
            "workflow_fetch": {
                "step": {
                    "type": "fetch",
                    "source": "whatsapp",
                    "since_days": "<int> OR use from_date/to_date (ISO dates)",
                    "chat_jids": "optional list — must be a subset of state.chats.scoped[].jid",
                },
            },
        },
    )


def refresh_gmail():
    from crm.models import Connection

    conn = Connection.objects.filter(source="gmail").first()
    meta = (conn.meta if conn else None) or {}
    _write_state(
        "gmail",
        {
            "status": (conn.status if conn else "disconnected"),
            "updated_at": _now(),
            "mode": meta.get("mode", "mock"),
            "user_id": meta.get("user_id"),
            "connected_account_id": meta.get("connected_account_id"),
            "workflow_fetch": {
                "step": {
                    "type": "fetch",
                    "source": "gmail",
                    "since_days": "<int> OR use from_date/to_date (ISO dates)",
                },
            },
        },
    )


def refresh(source=None):
    """Refresh one connector's state block, or both. Never raises."""
    try:
        if source in (None, "whatsapp"):
            refresh_whatsapp()
        if source in (None, "gmail"):
            refresh_gmail()
    except Exception as exc:
        logger.warning("connector state refresh failed: %s", exc)
